export const QUESTIONS = [
  {
    id: 1,
    level: "beginner",
    question: "تگ <a> در HTML برای چه کاری استفاده می‌شود؟",
    options: [
      "نمایش عکس",
      "لینک دادن به صفحه دیگر",
      "نوشتن تیتر",
      "تعریف جدول",
    ],
    correctAnswer: 1,
    score: 1,
  },
  {
    id: 2,
    level: "beginner",
    question: "کدام ویژگی CSS برای تغییر رنگ متن است؟",
    options: ["background-color", "color", "font-size", "text-align"],
    correctAnswer: 1,
    score: 1,
  },
  {
    id: 3,
    level: "beginner",
    question: "در HTML تگ <img> چه ویژگی‌ای برای آدرس تصویر دارد؟",
    options: ["src", "href", "alt", "title"],
    correctAnswer: 0,
    score: 1,
  },
  {
    id: 4,
    level: "beginner",
    question: "کدام یک از ویژگی‌های CSS باعث وسط‌چین شدن متن می‌شود؟",
    options: [
      "text-align: center",
      "align-items: center",
      "justify-content: center",
      "margin: auto",
    ],
    correctAnswer: 0,
    score: 1,
  },
  {
    id: 5,
    level: "beginner",
    question: "کدام یک از تگ‌های HTML برای تیتر اصلی صفحه استفاده می‌شود؟",
    options: ["<p>", "<h1>", "<span>", "<title>"],
    correctAnswer: 1,
    score: 1,
  },
  {
    id: 6,
    level: "beginner",
    question: "کدام روش تعریف استایل داخلی در HTML است؟",
    options: [
      "فایل CSS",
      "تگ <style>",
      "ویژگی style در تگ‌ها",
      "کتابخانه بوت‌استرپ",
    ],
    correctAnswer: 2,
    score: 1,
  },
  {
    id: 7,
    level: "beginner",
    question: "در جاوااسکریپت کدام نوع متغیر می‌تواند تغییر نکند؟",
    options: ["let", "var", "const", "function"],
    correctAnswer: 2,
    score: 1,
  },
  {
    id: 8,
    level: "beginner",
    question: "کدام مورد برای تعریف تابع در جاوااسکریپت صحیح است؟",
    options: [
      "define function()",
      "function myFunc()",
      "func myFunc()",
      "create myFunc()",
    ],
    correctAnswer: 1,
    score: 1,
  },
  {
    id: 9,
    level: "beginner",
    question: "کدام زبان برای ساخت ظاهر سایت استفاده می‌شود؟",
    options: ["JavaScript", "HTML", "CSS", "PHP"],
    correctAnswer: 2,
    score: 1,
  },
  {
    id: 10,
    level: "beginner",
    question: "کدام یک برای ساخت لیست مرتب استفاده می‌شود؟",
    options: ["<ul>", "<li>", "<ol>", "<list>"],
    correctAnswer: 2,
    score: 1,
  },
  {
    id: 11,
    level: "intermediate",
    question: "فرق بین == و === در جاوااسکریپت چیست؟",
    options: [
      "هیچ فرقی ندارند",
      "== نوع داده را بررسی نمی‌کند ولی === بررسی می‌کند",
      "=== برای مقایسه object است",
      "== برای تابع‌ها است",
    ],
    correctAnswer: 1,
    score: 2,
  },
  {
    id: 12,
    level: "intermediate",
    question: "کدام گزینه یک ویژگی Flexbox نیست؟",
    options: ["justify-content", "align-items", "flex-grow", "grid-template"],
    correctAnswer: 3,
    score: 2,
  },
  {
    id: 13,
    level: "intermediate",
    question: "کدام حالت موقعیت‌دهی در CSS باعث می‌شود عنصر از flow خارج شود؟",
    options: ["relative", "fixed", "static", "inherit"],
    correctAnswer: 1,
    score: 2,
  },
  {
    id: 14,
    level: "intermediate",
    question:
      "کدام یکی از متدهای جاوااسکریپت برای تبدیل string به عدد استفاده می‌شود؟",
    options: ["parseInt", "stringify", "join", "toFixed"],
    correctAnswer: 0,
    score: 2,
  },
  {
    id: 15,
    level: "intermediate",
    question: "در ری‌اکت، از چه hook برای مدیریت state استفاده می‌شود؟",
    options: ["useEffect", "useState", "useRef", "useMemo"],
    correctAnswer: 1,
    score: 2,
  },
  {
    id: 16,
    level: "intermediate",
    question: "برای شرط گذاشتن در JSX از چه چیزی استفاده می‌کنیم؟",
    options: ["if-else", "switch", "ternary operator", "for loop"],
    correctAnswer: 2,
    score: 2,
  },
  {
    id: 17,
    level: "intermediate",
    question: "در جاوااسکریپت، متد filter چه کاری انجام می‌دهد؟",
    options: [
      "فیلتر کردن آرایه طبق شرط",
      "تبدیل string",
      "ایجاد شیء جدید",
      "اضافه کردن آیتم به آرایه",
    ],
    correctAnswer: 0,
    score: 2,
  },
  {
    id: 18,
    level: "intermediate",
    question: "چطور یک کلاس را در JSX به تگ HTML اضافه می‌کنیم؟",
    options: ["class", "classname", "className", "class-name"],
    correctAnswer: 2,
    score: 2,
  },
  {
    id: 19,
    level: "intermediate",
    question: "کدام ویژگی در CSS برای متحرک‌سازی استفاده می‌شود؟",
    options: [
      "animation",
      "hover",
      "transition",
      "both animation and transition",
    ],
    correctAnswer: 3,
    score: 2,
  },
  {
    id: 20,
    level: "intermediate",
    question: "کدام یکی از انواع اسکوپ‌ها در JS درست است؟",
    options: [
      "Global, Local, Block",
      "Public, Private",
      "Global, Static",
      "Static, Instance",
    ],
    correctAnswer: 0,
    score: 2,
  },
  {
    id: 21,
    level: "advanced",
    question: "کدام یکی از مزایای استفاده از React.memo است؟",
    options: [
      "افزایش رندر",
      "جلوگیری از رندر غیر ضروری",
      "استفاده از useEffect",
      "ساخت context",
    ],
    correctAnswer: 1,
    score: 3,
  },
  {
    id: 22,
    level: "advanced",
    question: "در جاوااسکریپت، Promise چیست؟",
    options: [
      "تابع ریاضی",
      "مکانیزم مدیریت عملیات async",
      "نوع جدید متغیر",
      "کتابخانه",
    ],
    correctAnswer: 1,
    score: 3,
  },
  {
    id: 23,
    level: "advanced",
    question: "کدام ابزار برای مدیریت state در پروژه‌های بزرگ React مناسب است؟",
    options: ["useState", "Redux", "useRef", "DOM"],
    correctAnswer: 1,
    score: 3,
  },
  {
    id: 24,
    level: "advanced",
    question: "کدام روش باعث افزایش performance در رندر DOM می‌شود؟",
    options: [
      "استفاده زیاد از setState",
      "virtual DOM",
      "inline style",
      "CSS global",
    ],
    correctAnswer: 1,
    score: 3,
  },
  {
    id: 25,
    level: "advanced",
    question: "در React چه زمانی از useCallback استفاده می‌شود؟",
    options: [
      "برای ذخیره مقدار",
      "برای کش کردن کامپوننت",
      "برای جلوگیری از تعریف دوباره تابع",
      "برای اجرای تابع فقط یک بار",
    ],
    correctAnswer: 2,
    score: 3,
  },
  {
    id: 26,
    level: "advanced",
    question: "کدام ابزار برای تست کامپوننت‌های React استفاده می‌شود؟",
    options: ["Postman", "Jest", "Figma", "Git"],
    correctAnswer: 1,
    score: 3,
  },
  {
    id: 27,
    level: "advanced",
    question: "در پروژه‌های واقعی، SSR چه مزیتی دارد؟",
    options: [
      "افزایش حجم صفحه",
      "کند کردن لود",
      "افزایش SEO و لود اولیه",
      "کاهش رندر سمت سرور",
    ],
    correctAnswer: 2,
    score: 3,
  },
  {
    id: 28,
    level: "advanced",
    question: "کدام ساختار برای dynamic import در React است؟",
    options: [
      "import 'module'",
      "require('module')",
      "import('module')",
      "load('module')",
    ],
    correctAnswer: 2,
    score: 3,
  },
  {
    id: 29,
    level: "advanced",
    question: "tree shaking در webpack به چه معناست؟",
    options: [
      "حذف استایل‌ها",
      "کاهش تصاویر",
      "حذف کدهای استفاده نشده",
      "کم کردن حجم فایل HTML",
    ],
    correctAnswer: 2,
    score: 3,
  },
  {
    id: 30,
    level: "advanced",
    question: "کدام مورد زیر بهترین روش lazy load تصاویر در React است؟",
    options: [
      "استفاده از setTimeout",
      "استفاده از IntersectionObserver",
      "load بعد از رفرش",
      "غیرفعال کردن تصاویر",
    ],
    correctAnswer: 1,
    score: 3,
  },
];
