export const QUESTIONS = [
  {
    id: 1,
    level: "Beginner",
    question: "What is the <a> tag used for in HTML?",
    options: [
      "Displaying an image",
      "Linking to another page",
      "Writing a heading",
      "Defining a table",
    ],
    correctAnswer: 1,
    score: 1,
  },
  {
    id: 2,
    level: "Beginner",
    question: "Which CSS property changes text color?",
    options: ["background-color", "color", "font-size", "text-align"],
    correctAnswer: 1,
    score: 1,
  },
  {
    id: 3,
    level: "Beginner",
    question: "Which attribute in the <img> tag specifies the image URL?",
    options: ["src", "href", "alt", "title"],
    correctAnswer: 0,
    score: 1,
  },
  {
    id: 4,
    level: "Beginner",
    question: "Which CSS property centers text horizontally?",
    options: [
      "text-align: center",
      "align-items: center",
      "justify-content: center",
      "margin: auto",
    ],
    correctAnswer: 0,
    score: 1,
  },
  {
    id: 5,
    level: "Beginner",
    question: "Which HTML tag is used for the main page heading?",
    options: ["<p>", "<h1>", "<span>", "<title>"],
    correctAnswer: 1,
    score: 1,
  },
  {
    id: 6,
    level: "Beginner",
    question: "Which method defines inline styles in HTML?",
    options: [
      "CSS file",
      "<style> tag",
      "style attribute in tags",
      "Bootstrap library",
    ],
    correctAnswer: 2,
    score: 1,
  },
  {
    id: 7,
    level: "Beginner",
    question: "Which JavaScript variable type cannot be changed?",
    options: ["let", "var", "const", "function"],
    correctAnswer: 2,
    score: 1,
  },
  {
    id: 8,
    level: "Beginner",
    question: "Which syntax correctly defines a function in JavaScript?",
    options: [
      "define function()",
      "function myFunc()",
      "func myFunc()",
      "create myFunc()",
    ],
    correctAnswer: 1,
    score: 1,
  },
  {
    id: 9,
    level: "Beginner",
    question: "Which language is used to design a website's layout?",
    options: ["JavaScript", "HTML", "CSS", "PHP"],
    correctAnswer: 2,
    score: 1,
  },
  {
    id: 10,
    level: "Beginner",
    question: "Which tag is used to create an ordered list?",
    options: ["<ul>", "<li>", "<ol>", "<list>"],
    correctAnswer: 2,
    score: 1,
  },
  {
    id: 11,
    level: "Intermediate",
    question: "What is the difference between == and === in JavaScript?",
    options: [
      "No difference",
      "== does not check type, === does",
      "=== compares objects",
      "== is for functions",
    ],
    correctAnswer: 1,
    score: 2,
  },
  {
    id: 12,
    level: "Intermediate",
    question: "Which is NOT a Flexbox property?",
    options: ["justify-content", "align-items", "flex-grow", "grid-template"],
    correctAnswer: 3,
    score: 2,
  },
  {
    id: 13,
    level: "Intermediate",
    question: "Which CSS position removes an element from the normal flow?",
    options: ["relative", "fixed", "static", "inherit"],
    correctAnswer: 1,
    score: 2,
  },
  {
    id: 14,
    level: "Intermediate",
    question: "Which JavaScript method converts a string to a number?",
    options: ["parseInt", "stringify", "join", "toFixed"],
    correctAnswer: 0,
    score: 2,
  },
  {
    id: 15,
    level: "Intermediate",
    question: "Which React hook is used for state management?",
    options: ["useEffect", "useState", "useRef", "useMemo"],
    correctAnswer: 1,
    score: 2,
  },
  {
    id: 16,
    level: "Intermediate",
    question: "How do you conditionally render in JSX?",
    options: ["if-else", "switch", "ternary operator", "for loop"],
    correctAnswer: 2,
    score: 2,
  },
  {
    id: 17,
    level: "Intermediate",
    question: "What does the JavaScript filter method do?",
    options: [
      "Filters an array based on a condition",
      "Converts a string",
      "Creates a new object",
      "Adds an item to an array",
    ],
    correctAnswer: 0,
    score: 2,
  },
  {
    id: 18,
    level: "Intermediate",
    question: "How do you add a class to an HTML tag in JSX?",
    options: ["class", "classname", "className", "class-name"],
    correctAnswer: 2,
    score: 2,
  },
  {
    id: 19,
    level: "Intermediate",
    question: "Which CSS property is used for animations?",
    options: [
      "animation",
      "hover",
      "transition",
      "both animation and transition",
    ],
    correctAnswer: 3,
    score: 2,
  },
  {
    id: 20,
    level: "Intermediate",
    question:
      "Which of the following is a correct type of scope in JavaScript?",
    options: [
      "Global, Local, Block",
      "Public, Private",
      "Global, Static",
      "Static, Instance",
    ],
    correctAnswer: 0,
    score: 2,
  },
  {
    id: 21,
    level: "Advanced",
    question: "What is one benefit of using React.memo?",
    options: [
      "More re-renders",
      "Avoiding unnecessary re-renders",
      "Using useEffect",
      "Creating context",
    ],
    correctAnswer: 1,
    score: 3,
  },
  {
    id: 22,
    level: "Advanced",
    question: "What is a Promise in JavaScript?",
    options: [
      "A math function",
      "A mechanism for handling async operations",
      "A new variable type",
      "A library",
    ],
    correctAnswer: 1,
    score: 3,
  },
  {
    id: 23,
    level: "Advanced",
    question:
      "Which tool is suitable for state management in large React apps?",
    options: ["useState", "Redux", "useRef", "DOM"],
    correctAnswer: 1,
    score: 3,
  },
  {
    id: 24,
    level: "Advanced",
    question: "Which technique improves DOM rendering performance?",
    options: [
      "Using setState frequently",
      "Virtual DOM",
      "Inline styles",
      "Global CSS",
    ],
    correctAnswer: 1,
    score: 3,
  },
  {
    id: 25,
    level: "Advanced",
    question: "When should you use useCallback in React?",
    options: [
      "To store a value",
      "To cache a component",
      "To prevent redefining a function",
      "To run a function once",
    ],
    correctAnswer: 2,
    score: 3,
  },
  {
    id: 26,
    level: "Advanced",
    question: "Which tool is used to test React components?",
    options: ["Postman", "Jest", "Figma", "Git"],
    correctAnswer: 1,
    score: 3,
  },
  {
    id: 27,
    level: "Advanced",
    question: "What is the benefit of SSR in real-world projects?",
    options: [
      "Increases page size",
      "Slows loading",
      "Improves SEO and initial load",
      "Reduces server-side rendering",
    ],
    correctAnswer: 2,
    score: 3,
  },
  {
    id: 28,
    level: "Advanced",
    question: "Which syntax is used for dynamic import in React?",
    options: [
      "import 'module'",
      "require('module')",
      "import('module')",
      "load('module')",
    ],
    correctAnswer: 2,
    score: 3,
  },
  {
    id: 29,
    level: "Advanced",
    question: "What does tree shaking in webpack mean?",
    options: [
      "Removing styles",
      "Reducing images",
      "Removing unused code",
      "Minifying HTML",
    ],
    correctAnswer: 2,
    score: 3,
  },
  {
    id: 30,
    level: "Advanced",
    question: "What is the best way to lazy load images in React?",
    options: [
      "Using setTimeout",
      "Using IntersectionObserver",
      "Loading after refresh",
      "Disabling images",
    ],
    correctAnswer: 1,
    score: 3,
  },
];
